config/routes.rb
TaylorsvilleClassSchedule::Application.routes.draw do
  resources :semester_schedules

  resources :semester_classes

  resources :time_slots

  resources :semesters

  resources :school_classes

  resources :departments

  devise_for :users

  get "home/index"
  post "home/updateClasses"

  
  root :to => "home#index"
end

app/controllers/school_classes_controller.rb
class SchoolClassesController < ApplicationController
  # GET /school_classes
  # GET /school_classes.json
  def index
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @school_classes = SchoolClass.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @school_classes }
    end
  end

  # GET /school_classes/1
  # GET /school_classes/1.json
  def show
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @school_class = SchoolClass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school_class }
    end
  end

  # GET /school_classes/new
  # GET /school_classes/new.json
  def new
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @school_class = SchoolClass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school_class }
    end
  end

  # GET /school_classes/1/edit
  def edit
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @school_class = SchoolClass.find(params[:id])
  end

  # POST /school_classes
  # POST /school_classes.json
  def create
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @school_class = SchoolClass.new(params[:school_class])

    respond_to do |format|
      if @school_class.save
        format.html { redirect_to @school_class, notice: 'School class was successfully created.' }
        format.json { render json: @school_class, status: :created, location: @school_class }
      else
        format.html { render action: "new" }
        format.json { render json: @school_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /school_classes/1
  # PUT /school_classes/1.json
  def update
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @school_class = SchoolClass.find(params[:id])

    respond_to do |format|
      if @school_class.update_attributes(params[:school_class])
        format.html { redirect_to @school_class, notice: 'School class was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_classes/1
  # DELETE /school_classes/1.json
  def destroy
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @school_class = SchoolClass.find(params[:id])
    @school_class.destroy

    respond_to do |format|
      format.html { redirect_to school_classes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/school_classes_helper.rb
module SchoolClassesHelper
end

app/views/school_classes/_form.html.erb
<%= form_for(@school_class) do |f| %>
  <% if @school_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school_class.errors.count, "error") %> prohibited this school_class from being saved:</h2>

      <ul>
      <% @school_class.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br />
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_field :Description %>
  </div>
  <div class="field">
    <%= f.label :DepartmentId %><br />
    <%= f.number_field :DepartmentId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/school_classes/edit.html.erb
<h1>Editing school_class</h1>

<%= render 'form' %>

<%= link_to 'Show', @school_class %> |
<%= link_to 'Back', school_classes_path %>

app/views/school_classes/index.html.erb
<h1>Listing school_classes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Departmentid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @school_classes.each do |school_class| %>
  <tr>
    <td><%= school_class.Name %></td>
    <td><%= school_class.Description %></td>
    <td><%= school_class.DepartmentId %></td>
    <td><%= link_to 'Show', school_class %></td>
    <td><%= link_to 'Edit', edit_school_class_path(school_class) %></td>
    <td><%= link_to 'Destroy', school_class, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New School class', new_school_class_path %>

app/views/school_classes/new.html.erb
<h1>New school_class</h1>

<%= render 'form' %>

<%= link_to 'Back', school_classes_path %>

app/views/school_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @school_class.Name %>
</p>

<p>
  <b>Description:</b>
  <%= @school_class.Description %>
</p>

<p>
  <b>Departmentid:</b>
  <%= @school_class.DepartmentId %>
</p>


<%= link_to 'Edit', edit_school_class_path(@school_class) %> |
<%= link_to 'Back', school_classes_path %>