config/routes.rb
TaylorsvilleClassSchedule::Application.routes.draw do
  resources :semester_schedules

  resources :semester_classes

  resources :time_slots

  resources :semesters

  resources :school_classes

  resources :departments

  devise_for :users

  get "home/index"
  post "home/updateClasses"

  
  root :to => "home#index"
end

app/controllers/semester_classes_controller.rb
class SemesterClassesController < ApplicationController
  # GET /semester_classes
  # GET /semester_classes.json
  def index
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @semester_classes = SemesterClass.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @semester_classes }
    end
  end

  # GET /semester_classes/1
  # GET /semester_classes/1.json
  def show
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @semester_class = SemesterClass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @semester_class }
    end
  end

  # GET /semester_classes/new
  # GET /semester_classes/new.json
  def new
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @semester_class = SemesterClass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @semester_class }
    end
  end

  # GET /semester_classes/1/edit
  def edit
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @semester_class = SemesterClass.find(params[:id])
  end

  # POST /semester_classes
  # POST /semester_classes.json
  def create
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @semester_class = SemesterClass.new(params[:semester_class])

    respond_to do |format|
      if @semester_class.save
        format.html { redirect_to @semester_class, notice: 'Semester class was successfully created.' }
        format.json { render json: @semester_class, status: :created, location: @semester_class }
      else
        format.html { render action: "new" }
        format.json { render json: @semester_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /semester_classes/1
  # PUT /semester_classes/1.json
  def update
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @semester_class = SemesterClass.find(params[:id])

    respond_to do |format|
      if @semester_class.update_attributes(params[:semester_class])
        format.html { redirect_to @semester_class, notice: 'Semester class was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @semester_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semester_classes/1
  # DELETE /semester_classes/1.json
  def destroy
    if(!checkAdmin())
      redirect_to "/", notice: 'Admin only!'
      return
    end
    @semester_class = SemesterClass.find(params[:id])
    @semester_class.destroy

    respond_to do |format|
      format.html { redirect_to semester_classes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/semester_classes_helper.rb
module SemesterClassesHelper
end

app/views/semester_classes/_form.html.erb
<%= form_for(@semester_class) do |f| %>
  <% if @semester_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@semester_class.errors.count, "error") %> prohibited this semester_class from being saved:</h2>

      <ul>
      <% @semester_class.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :SemesterId %><br />
    <%= f.number_field :SemesterId %>
  </div>
  <div class="field">
    <%= f.label :TimeSlotId %><br />
    <%= f.number_field :TimeSlotId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/semester_classes/edit.html.erb
<h1>Editing semester_class</h1>

<%= render 'form' %>

<%= link_to 'Show', @semester_class %> |
<%= link_to 'Back', semester_classes_path %>

app/views/semester_classes/index.html.erb
<h1>Listing semester_classes</h1>

<table>
  <tr>
    <th>Semester</th>
    <th>Timeslotid</th>
	<th>SchoolClassid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @semester_classes.each do |semester_class| %>
  <tr>
    <td><%= semester_class.Semester.Name %></td>
    <td><%= semester_class.TimeSlot.Name %></td>
	<td><%= semester_class.SchoolClass.Name %></td>
    <td><%= link_to 'Show', semester_class %></td>
    <td><%= link_to 'Edit', edit_semester_class_path(semester_class) %></td>
    <td><%= link_to 'Destroy', semester_class, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Semester class', new_semester_class_path %>

app/views/semester_classes/new.html.erb
<h1>New semester_class</h1>

<%= render 'form' %>

<%= link_to 'Back', semester_classes_path %>

app/views/semester_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Semesterid:</b>
  <%= @semester_class.SemesterId %>
</p>

<p>
  <b>Timeslotid:</b>
  <%= @semester_class.TimeSlotId %>
</p>


<%= link_to 'Edit', edit_semester_class_path(@semester_class) %> |
<%= link_to 'Back', semester_classes_path %>