config/routes.rb
TaylorsvilleClassSchedule::Application.routes.draw do
  resources :semester_schedules

  resources :semester_classes

  resources :time_slots

  resources :semesters

  resources :school_classes

  resources :departments

  devise_for :users

  get "home/index"
  post "home/updateClasses"

  
  root :to => "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaylorsvilleClassSchedule</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
			<div class="content-wrapper">
				<div class="float-left">
					<p class="site-title"><%= link_to "Taylorsville Schedule Change", home_index_path %></p>
					<% if(user_signed_in?) %>
						<ul>
							<li><%= link_to "Student Changes", semester_schedules_path %></li>
							<% if(current_user.isadmin) %>
							<li><%= link_to "Semester Classes", semester_classes_path %></li>
							<li><%= link_to "Departments", departments_path %></li>
							<li><%= link_to "Classes", school_classes_path %></li>
							<li><%= link_to "Time Slots", time_slots_path %></li>
							<li><%= link_to "Semesters", semesters_path %></li>
							<% end %>
						</ul>
					<% end %>
				</div>
				<div class="float-right">
				<section id="login">
					<% if user_signed_in? %>
						Welcome <%= current_user.email %>!
						<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>	
					<% else %>
						<%= link_to "Sign In", new_user_session_path %>
					<% end %>
					</div>
				</section>
				<nav>
				</nav>
			</div>
		</header>
		<div id="body">
			<section class="content-wrapper main-content clear-fix">
				<%= yield %>
			</section>
		</div>
</body>
</html>